### ISSUE TITLE
Modal CSS transitions lag caused by React's CSSTransitionGroup

### ISSUE THREAD

**Issue by samzhao** [elementalui/elemental#27] opened 2015-06-15 18:11 UTC
If you open and close the modal a couple times within 5 seconds, you'll see a warning like this:

```
Warning: transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition.
```

Although it's "only a warning", and everything is still functional as expected, but it causes the transition to lag a bit.

This is a bug that needs to be fixed by the React team, but in the mean time could we use Khan Academy's [TimeoutTransitionGroup](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx).

Let me know if you guys have encountered the same problem or have had some discussions on this topic, and if I should create a PR for it - I personally am not sure if the TimeoutTransitionGroup is going to solve the problem, but a lot of other people have had success with it.

**Comment by jossmac** [comment] 2015-06-16 00:05
@dcousens would you mind looking into this?

**Comment by jossmac** [comment] 2015-07-13 00:21
We've made significant updates since this was logged and I can't reproduce. @samzhao would you mind getting latest and letting us know if you're still seeing this issue?

**Comment by JedWatson** [comment] 2015-07-29 08:12
Closing, we can't reproduce. @samzhao please let us know if this is still an issue.

**Closed by JedWatson** 2015-07-29 08:12 UTC
Labels: bug, discussion

**Comment by samzhao** [comment] 2015-08-02 19:20
Hey @jossmac and @JedWatson, sorry for the late response. I just tested it again with the latest version, and it works perfectly now - thanks!
